project_id = "vtfpwvzufffmtnovvilx"

[functions.kb-embeddings]
verify_jwt = false

[functions.trade-execute]
verify_jwt = true

[functions.stats-kpis]
verify_jwt = true

[functions.bot-trading]
verify_jwt = true