project_id = "vtfpwvzufffmtnovvilx"

[functions.decrypt-brokerage-credentials]
verify_jwt = true

[functions.oracle-realtime-data]
verify_jwt = true

[functions.detect-account-type]
verify_jwt = true

[functions.kb-embeddings]
verify_jwt = false

[functions.trade-execute]
verify_jwt = true

[functions.stats-kpis]
verify_jwt = false

[functions.bot-trading]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.create-portal-session]
verify_jwt = true

[functions.billing-webhook]
verify_jwt = false

[functions.analyst-voice-unified]
verify_jwt = true

[functions.brokerage-sync]
verify_jwt = true

[functions.alpaca-sync]
verify_jwt = true

[functions.market-data-sync]
verify_jwt = false