// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtfpwvzufffmtnovvilx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0ZnB3dnp1ZmZmbXRub3Z2aWx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MTg5ODcsImV4cCI6MjA3MjM5NDk4N30.QCdlv2PkBwOmUOSitFq9xx6iM_6uNEkvB0AvrJVr2yU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});